spring:
  application:
    name: distributelock
  datasource:
    url: jdbc:mysql://localhost:3306/tuacydev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: com.tuacy.study.distributelock.model
  mapperLocations: classpath:mapper/*.xml
